#service: bug100
runtime: nodejs18

instance_class: F4

automatic_scaling:
  target_cpu_utilization: 0.8
  min_instances: 6
  max_instances: 15
  max_pending_latency: 600ms

handlers:
  - url: '.*\.php$'
    static_files: public/404.html
    upload: public/404.html
  - url: /_next/static
    static_dir: build/static
    expiration: 10m
    http_headers:
      X-handler-Header: true
  - url: /static
    static_dir: static
    expiration: 10m
    http_headers:
      X-handler-Header: true
  - url: /sw.js
    static_files: static/js/sw.js
    upload: static/js/sw.js
    expiration: 10m
  - url: /.*
    secure: always
    redirect_http_response_code: 301
    script: auto