const FriendlyJobSerpCreate = require("./FriendlyJobSerpCreate");

let KeywordsUk = [
    "home based",
    "part time",
    "delivery driver",
    "working from home",
    "from home",
    "no experience",
    "work from home",
    "driver",
    "nhs no experience",
    "warehouse",
    "supermarket",
    "data entry from home",
    "near me",
    "amazon",
    "cleaner",
    "tesco",
    "nhs",

    "airport",
    "cleaning",
    "remote",
    "night tesco",
    "cash hand",
    "nhs delivery driver",
    "night shift",
    "drivers",
    "small van driver",
    "chemist driver",

    "nhs driver",
    "call center",
    "packing warehouse",
    "partime",
    "online",
    "receptionist",
    "passport office",
    "senior citizens",
    "cash hand cleaning",
    "packing from home",
    "hospital",
    "government",
    "immediate start",
    "asda",
    "part time packer",
    "parttime",

    "driving",
    "temp",
    "at home",
    "chocolate factory",
    "hgv driver",
    "hotel",
    "packing boxes from home",
    "construction",
    "caregiver",
    "grocery store",
    "cash only",
    "full time",
    "warehouse worker",
    "weekend",
    "factory",
    "blood delivery driver",
    "security guard",
    "local",
    "walmart",
    "forklift driver",
    "opportunities",
    "nanny",
    "post office",
    "cashier",
    "local part time",
    "council staff",
    "internships",

    "admin",
    "driver vacancy",
    "support worker",
    "cleaners",
    "administration",
    "hospital cleaning",
    "seniors part time",
    "dog walker",
    "warehouse operative",

    "packaging",
    "retirement",
    "mcdonalds",
    "weekends only",
    "costco",
    "security",
    "office cleaning",

    "courier driver",
    "data entry",
    "restaurant",
    "chemist delivery driver",
    "school cleaning",
    "packer",
    "data entry working from home",
    "long distance van driver",
    "hospital front desk",
    "nhs from home",
    "cruise ship",
    "sainsburry",
    "costco warehouse",
    "van driver",
    "packing",
    "school",
    "council bin man",
    "house sitting",
    "sitter hospital",
    "freelance",
    "part time mailroom",
    "same day pay",
    "late night stocker",
    "saturday and sunday",
    "night",
    "truck driver",
    "railway",
    "cleaner wanted",
    "heathrow airport",
    "canada post",
    "mining",
    "lmia",
    "general labourer",
    "crime scene assistant",
    "security officer",
    "logistics",
    "long distance van driving",
    "hospital porter",
    "agency",
    "housekeeper",
    "librarian assistant",
    "retail",
    "customer service",
    "morrisons",
    "nhs cleaning",
    "home packing",
    "seniors",
    "welder",
    "no experience needed",
    "adecco",
    "housekeeping",
    "maintenance",
    "royal mail",
    "assistant to elderly",
    "aldi",
    "food packing",
    "london",
    "temporary",
    "office",
    "primark",
    "volunteer",
    "factory worker",
    "no qualifications",
    "packing at home",
    "lidl",
    "lorry driver",
    "virtual assistant",
    "bakery",
    "part time no experience",
    "apprenticeship",
    "early morning postal worker",
    "council driving",
    "kfc",
    "library no experience",
    "welding",
    "working from home part time",
    "from home data entry",
    "care assistant",
    "evening",
    "electrician",
    "coca cola",
    "hgv",
    "staffline",
    "mcdonald",
    "police",
    "worker",
    "manager",
    "banking",
    "hospital cleaner",
    "teacher assistant",

    "same day cash",
    "teaching assistant",
    "handyman",
    "house cleaning",
    "costco part time",
    "forklift",
    "nurse",
    "dpd",
    "amazon warehouse",
    "bus driver",
    "night shift tesco",
    "farming",
    "youth",
    "all",
    "council part time",
    "farm",
    "library assistant",
    "chef",
    "sales",
    "school hours",
    "education",
    "saturday",
    "local near me",
    "apprentice",
    "night security officer",
    "part time driver",
    "brampton",
    "carpenter",
    "office admin",
    "mail sorter",
    "dishwasher",
    "cash paying",
    "fedex",
    "bricklayer",
    "delivery drivers",
    "stay at home",
    "nhs care assistant",
    "part time from home",
    "self employed",
    "labourer",
    "bricklayers wanted",
    "nhs driving",
    "full-time",
    "van driving",
    "visa sponsorship",
    "bank",
    "graduate",
    "internship",
    "dwp",
    "courier",
    "nhs hospital porter",
    "school cleaner",
    "warehousing",
    "mystery shopper",
    "forklift operator",
    "monday to friday",
    "cash paid",
    "pet sitter",
    "school dinner lady",
    "royal mil",
    "painter",
    "meter reader",
    "dhl",
    "car delivery",
    "phlebotomist",
    "urgent",
    "clerk",
    "driver courier",
    "construction worker",
    "part time tesco",
    "delivering cars",
    "cash gigs near me",
    "part-time",
    "stay home",
    "nhs porter",
    "groundworker",
    "medical courier",
    "charity",
    "health and safety",
    "family support worker",
    "school administrator",
    "sewing",
    "care home",
    "care worker",
    "cleaning office",
    "au pair",
    "personal assistant",
    "driver-courier",
    "gatwick airport",
    "high pay",
    "mental health",
    "general labour",
    "driver assistant",
    "nhs blood driver",
    "genaral",
    "delivery",
    "light packaging",
    "primary school",
    "civil service",
    "older people",
    "plumbing",
    "telehandler",
    "ups",
    "mcdonald part time",
    "house sitter",
    "weekends",
    "agriculture",
    "general worker",
    "private caregiver",
    "call centre",
    "nhs work from home",
    "kitchen porter",
    "parcel delivery",
    "teacher",
    "cleaning hospital",
    "air canada",
    "nhs receptionist",
    "postal worker",
    "police officer",
    "home care",
    "weekend only",
    "waitress",
    "shop rite",
    "over fifties",
    "warehouse staff",
    "train station",
    "night driver",
    "machine operator",
    "ikea",
    "immediate starting",
    "pertemps",
    "forklift drivers",
    "cash pay",
    "home",
    "postman",
    "baby cuddler",
    "catering",
    "photographer",
    "sponsored visa",
    "creative",
    "hospitality",
    "blue arrow",
    "supervisor",
    "operations manager",
    "from home call center",
    "project manager",
    "warehouse operative.",
    "administrator",
    "vehicle driver",
    "drivers mate",
    "paralegal",
    "caretaker",
    "manchester airport",
    "transcription",
    "part time evening",
    "hotel cleaning",
    "elderly",
    "french speaking",
    "exam invigilator",
    "bear",
    "part time postal worker",
    "hotel housekeeper",
    "care",
    "porter",
    "school cleaners",
    "bmw",
    "birmingham",
    "waitrose",
    "car driver",
    "cash",
    "school kitchen assistant",
    "tim hortons",
    "cash hand part time",
    "warehouse workers",
    "mark and spencer",
    "cash  hand part time",
    "translator",
    "own car delivery",
    "daycare",
    "service canada",
    "office cleaner",
    "personal shopper",
    "electricians",
    "labourers",
    "mechanic",
    "data entry home",
    "morning cleaner",
    "gardener",
    "estate agent",
    "general cleaner",
    "at home customer service",
    "class 1 driver",
    "data entry at home",
    "part time cleaning",
    "laundry attendant",
    "leicester",
    "birmingham airport",
    "at home part time",
    "burger king",
    "courier delivery driver",
    "early morning",
    "office receptionist",
    "night stocker",
    "no experience no experience",
    "nhs admin",
    "at home researcher",
    "council",
    "fitter",
    "saturday sunday",
    "schools",
    "train driver",
    "environmental",
    "art",
    "from home part time",
    "house keeping",
    "non experience",
    "airline baggage coordinator",
    "gardening",
    "immediate start near me",
    "kfc part time",
    "prison",
    "police records specialist",
    "term time",
    "laundry",
    "weekly pay",
    "no experience from home",
    "class 2 driver",
    "warehouse assistant",
    "laboratory",
    "coventry",
    "shuttle driver",
    "casual",
    "no experience immediate start",
    "no experience part time",
    "electrician apprentice",
    "warehouse forklift operator",
    "argos",
    "remote from home",
    "bookkeeper",
    "passport",
    "kitchen assistant",
    "part time government",
    "superstore",
    "hr",
    "council cleaning",
    "nhs apprenticeship",
    "nursing",
    "paid cash",
    "manufacturing",
    "handyman helper",
    "london underground",
    "part times",
    "company driver",
    "teachers assistant",
    "funeral",
    "social worker",
    "luton airport",
    "animal",
    "human resources",
    "flexible",
    "nhs part time",
    "truck drivers",
    "no experience high salary",
    "shop assistant",
    "starbucks",
    "librarian",
    "recruitment",
    "greggs",
    "assembler",
    "hgv class 1",
    "bristol",
    "co op",
    "night cleaning",
    "7.5 tonne driver",
    "park ranger",
    "counsellor",
    "car delivery driver",
    "live-",
    "interpreter",
    "sports",
    "fruit packer",
    "psw",
    "canada",
    "home delivery driver",
    "insurance",
    "part time remote",
    "dog walking",
    "office assistant",
    "seasonal",
    "data entry clerk",
    "security guards",
    "bar staff",
    "nhs  from home",
    "front desk receptionist",
    "chefs",
    "newcastle",
    "no experience nhs",
    "supermarkets",
    "trainee train driver",
    "merchandiser",
    "baggage handler",
    "child care assistant",
    "museum",
    "trainee",
    "bricklaying",
    "hospital nhs",
    "medical driver",
    "g4s",
    "360 excavator",
    "morrison",
    "nursery",
    "spanish speaking",
    "healthcare",
    "hotel cleaner",

    "live carer"
]

let CitiesUK = [
    "Buckingham",
    "Ferndown",
    "Halesowen",
    "Peterlee",
    "Morecambe",
    "March",
    "Lytham Saint Annes",
    "Penzance",
    "Bishop Auckland",
    "North Shields",
    "Epping",
    "Royal Borough of Kensington and Chelsea",
    "Mildenhall",
    "Batley",
    "Tipton",
    "Consett",
    "Bridgnorth",
    "Bideford",
    "Belper",
    "Long Eaton",
    "Helston",
    "Wymondham",
    "Thames Ditton",
    "Leicester",
    "Crawley",
    "Luton",
    "Stoke-on-Trent",
    "Chester",
    "Doncaster",
    "Gloucester",
    "Huddersfield",
    "Chertsey",
    "Aylesbury",
    "Chesterfield",
    "Wigan",
    "Macclesfield",
    "Redhill",
    "Oldham",
    "Mansfield",
    "Royal Leamington Spa",
    "Gateshead",
    "Bicester",
    "Stafford",
    "Eastbourne",
    "Corby",
    "Wokingham",
    "Leatherhead",
    "Loughborough",
    "Sevenoaks",
    "Halifax",
    "Scarborough",
    "Windsor",
    "Lancaster",
    "Scunthorpe",
    "King's Lynn",
    "Dorchester",
    "Cirencester",
    "Burgess Hill",
    "Torquay",
    "Southport",
    "Grays",
    "Chatham",
    "St Albans",
    "Lichfield",
    "Sittingbourne",
    "Northallerton",
    "Hinckley",
    "Havant",
    "Worksop",
    "Skelmersdale",
    "Godalming",
    "Ascot",
    "Gravesend",
    "Stroud",
    "Market Harborough",
    "Kendal",
    "Newmarket",
    "Romsey",
    "Hartlepool",
    "Warminster",
    "Amersham",
    "Stamford",
    "Workington",
    "Bodmin",
    "Thatcham",
    "Oakham",
    "Potters Bar",
    "Stonehouse",
    "Heywood",
    "Wantage",
    "Saint Austell",
    "Kidlington",
    "Oswestry",
    "Ashby-de-la-Zouch",
    "Blandford Forum",
    "Morpeth",
    "Sandy",
    "Margate",
    "Wallingford",
    "Newton Aycliffe",
    "Saffron Walden",
    "Ilkeston",
    "Stowmarket",
    "Leek",
    "Sutton-in-Ashfield",
    "Billericay",
    "Addlestone",
    "Chesham",
    "Whitehaven",
    "Prescot",
    "Rayleigh",
    "Swanley",
    "Harpenden",
    "Crowborough",
    "Gerrards Cross",
    "Ryde",
    "Bletchley",
    "Arundel",
    "Buxton",
    "Bushey",
    "Maldon",
    "Knowsley",
    "Tiverton",
    "Winnersh",
    "Brackley",
    "Brierley Hill",
    "Woodbridge",
    "Felixstowe",
    "Towcester",
    "Louth",
    "Shipley",
    "Woodford",
    "Glastonbury",
    "Ramsgate",
    "Paignton",
    "Clevedon",
    "Lancing",
    "Uttoxeter",
    "Milton",
    "Waltham Cross",
    "Alderley Edge",
    "Newport Pagnell",
    "Spennymoor",
    "Nelson",
    "Alcester",
    "Midhurst",
    "Ross-on-Wye",
    "Leeds",
    "Nottingham",
    "Oxford",
    "York",
    "Warrington",
    "Plymouth",
    "Bolton",
    "Berkshire",
    "Newbury",
    "Dartford",
    "Lincoln",
    "Royal Tunbridge Wells",
    "Basildon",
    "Salford",
    "Blackpool",
    "Worthing",
    "Hatfield",
    "Huntingdon",
    "Walsall",
    "Shrewsbury",
    "Middlesbrough",
    "Bury",
    "Darlington",
    "Rochdale",
    "Bury Saint Edmunds",
    "Sunderland",
    "Abingdon",
    "Castle Donington",
    "Carlisle",
    "Staines-upon-Thames",
    "Stock",
    "Thirsk",
    "Didcot",
    "Eastleigh",
    "Stockton-on-Tees",
    "Nuneaton",
    "Stratford-upon-Avon",
    "Runcorn",
    "Reigate",
    "Haywards Heath",
    "Royston",
    "Knutsford",
    "Aldershot",
    "Farnham",
    "Brentford",
    "Kidderminster",
    "Sale",
    "Grantham",
    "Horley",
    "Coalville",
    "Folkestone",
    "Newton Abbot",
    "Weymouth",
    "Castleford",
    "Leighton Buzzard",
    "Alfreton",
    "Walton-on-Thames",
    "Malmesbury",
    "Uckfield",
    "Marlow",
    "Ripon",
    "Thetford",
    "Henley-on-Thames",
    "Winsford",
    "Droitwich Spa",
    "Malton",
    "Lowestoft",
    "Marlborough",
    "Beaconsfield",
    "West Malling",
    "Leyland",
    "Bury St Edmunds",
    "Frimley",
    "Hoddesdon",
    "Welwyn",
    "Lymington",
    "Exmouth",
    "Bourne",
    "Penrith",
    "Caterham",
    "Berkhamsted",
    "Melksham",
    "Hailsham",
    "Kenilworth",
    "Washington",
    "Matlock",
    "Shepton Mallet",
    "Saint Ives",
    "Saint Neots",
    "Tilbury",
    "Chandler's Ford",
    "Congleton",
    "Bootle",
    "Whitstable",
    "Wickford",
    "Shaftesbury",
    "Hexham",
    "Ilkley",
    "Retford",
    "Hedge End",
    "Broadstairs",
    "Princes Risborough",
    "Camborne",
    "Bristol",
    "Cambridge",
    "Coventry",
    "Newcastle upon Tyne",
    "Northampton",
    "Chelmsford",
    "Norwich",
    "Portsmouth",
    "Basingstoke",
    "Watford",
    "Slough",
    "West Bromwich",
    "Bournemouth",
    "Bath",
    "Stockport",
    "Ipswich",
    "Bedford",
    "Colchester",
    "Hull",
    "Poole",
    "Worcester",
    "Taunton",
    "Barnsley",
    "Saint Albans",
    "Harlow",
    "Rotherham",
    "Crewe",
    "Sutton",
    "Kettering",
    "Warwick",
    "Canterbury",
    "Durham",
    "Rugby",
    "Hereford",
    "Richmond",
    "Andover",
    "Redditch",
    "Camberley",
    "Truro",
    "Weston-super-Mare",
    "Hastings",
    "Hertford",
    "Chorley",
    "Christchurch",
    "Hove",
    "Rochester",
    "Newport",
    "Barrow-in-Furness",
    "East Grinstead",
    "Borehamwood",
    "Tewkesbury",
    "Northwich",
    "Lewes",
    "Sutton Coldfield",
    "Newark-on-Trent",
    "Barnstaple",
    "Boston",
    "Fleet",
    "Great Yarmouth",
    "Newcastle-under-Lyme",
    "Nantwich",
    "Letchworth Garden City",
    "Pontefract",
    "Evesham",
    "Skipton",
    "Devizes",
    "Spalding",
    "Bognor Regis",
    "Hook",
    "Wimborne Minster",
    "Thame",
    "Biggleswade",
    "Oldbury",
    "Keighley",
    "Falmouth",
    "Rickmansworth",
    "Clacton-on-Sea",
    "Wetherby",
    "Goole",
    "Rugeley",
    "Rushden",
    "Redruth",
    "Sunbury-on-Thames",
    "Ormskirk",
    "Stourbridge",
    "Smethwick",
    "Launceston",
    "Beeston",
    "Chard",
    "Darwen",
    "Wallasey",
    "Sleaford",
    "New Milton",
    "Hungerford",
    "Sandbach",
    "Radlett",
    "Sidmouth",
    "Haydock",
    "Oxted",
    "Cheshunt",
    "Immingham",
    "Willenhall",
    "Liskeard",
    "Fleetwood",
    "London",
    "Manchester",
    "Birmingham",
    "Swindon",
    "Reading",
    "Liverpool",
    "Sheffield",
    "Milton Keynes",
    "Southampton",
    "Brighton",
    "Guildford",
    "Peterborough",
    "Exeter",
    "Derby",
    "Croydon",
    "Stevenage",
    "Bradford",
    "Preston",
    "Maidstone",
    "Cheltenham",
    "Maidenhead",
    "High Wycombe",
    "Wakefield",
    "Winchester",
    "Wolverhampton",
    "Bracknell",
    "Solihull",
    "Salisbury",
    "Hemel Hempstead",
    "Woking",
    "Harrogate",
    "Telford",
    "Southend-on-Sea",
    "Ashford",
    "Horsham",
    "Blackburn",
    "Chichester",
    "Farnborough",
    "Banbury",
    "Epsom",
    "Fareham",
    "Burton upon Trent",
    "Yeovil",
    "Bedfordshire",
    "Altrincham",
    "Tamworth",
    "Dudley",
    "Weybridge",
    "Grimsby",
    "Cheshire",
    "Braintree",
    "Witney",
    "Wellingborough",
    "Saint Helens",
    "Bridgwater",
    "Wembley",
    "Birkenhead",
    "Brentwood",
    "Wilmslow",
    "Burnley",
    "Tonbridge",
    "Bishop's Stortford",
    "Trowbridge",
    "Dunstable",
    "Hitchin",
    "Daventry",
    "Egham",
    "Dorking",
    "Bromsgrove",
    "Ellesmere Port",
    "Cannock",
    "Dover",
    "Witham",
    "Ely",
    "Widnes",
    "Alton",
    "Petersfield",
    "Frome",
    "Waterlooville",
    "Lutterworth",
    "Cramlington",
    "Littlehampton",
    "Melton Mowbray",
    "Swadlincote",
    "Wednesbury",
    "Newquay",
    "Haverhill",
    "Accrington",
    "Great Malvern",
    "Ware",
    "Beverley",
    "Teddington",
    "Chipping Norton",
    "Ampthill"
]

let CitiesCA = [
    "Saint-Joseph-de-Beauce, Quebec, Canada",
    "Midland, Ontario, Canada",
    "Chesley, Ontario, Canada",
    "Saint-Felicien, Quebec, Canada",
    "Kenora, Ontario, Canada",
    "St-Tite, Quebec, Canada",
    "Marieville, Quebec, Canada",
    "Chicoutimi, Quebec, Canada",
    "Waterville, Quebec, Canada",
    "Virden, Manitoba, Canada",
    "Wingham, Ontario, Canada",
    "Rockglen, Saskatchewan, Canada",
    "Rouyn-Noranda, Quebec, Canada",
    "Gibsons, British Columbia, Canada",
    "Sainte-Anne-des-Plaines, Quebec, Canada",
    "Wadena, Saskatchewan, Canada",
    "Saint-Anselme, Quebec, Canada",
    "Tisdale, Saskatchewan, Canada",
    "Clavet, Saskatchewan, Canada",
    "Invermere, British Columbia, Canada",
    "Bromont, Quebec, Canada",
    "Beauceville, Quebec, Canada",
    "Chesterville, Ontario, Canada",
    "Little Current, Ontario, Canada",
    "Sainte-Anne-de-Bellevue, Quebec, Canada",
    "Bella Bella, British Columbia, Canada",
    "Craik, Saskatchewan, Canada",
    "Sainte-Catherine, Quebec, Canada",
    "Wunnummin Lake, Ontario, Canada",
    "Saint-Boniface-de-Shawinigan, Quebec, Canada",
    "Cote Saint-Luc, Quebec, Canada",
    "Mount Hope, Ontario, Canada",
    "Beauval, Saskatchewan, Canada",
    "Elgin, Ontario, Canada",
    "Chatsworth, Ontario, Canada",
    "L'Epiphanie, Quebec, Canada",
    "North Bay, Ontario, Canada",
    "Dublin, Ontario, Canada",
    "Stirling, Ontario, Canada",
    "Tadoussac, Quebec, Canada",
    "Saint-Basile-le-Grand, Quebec, Canada",
    "Kuujjuaq, Quebec, Canada",
    "Forest, Ontario, Canada",
    "Komoka, Ontario, Canada",
    "Capreol, Ontario, Canada",
    "South Lancaster, Ontario, Canada",
    "Pond Inlet, Nunavut, Canada",
    "Saint-Pascal, Quebec, Canada",
    "Quebec City, Quebec, Canada",
    "Saint-Constant, Quebec, Canada",
    "Saint-Cesaire, Quebec, Canada",
    "Stony Mountain, Manitoba, Canada",
    "Candiac, Quebec, Canada",
    "Armstrong, British Columbia, Canada",
    "Victoriaville, Quebec, Canada",
    "Eganville, Ontario, Canada",
    "Lincoln, Ontario, Canada",
    "Cabri, Saskatchewan, Canada",
    "La Malbaie, Quebec, Canada",
    "St. Catharines, Ontario, Canada",
    "La Ronge, Saskatchewan, Canada",
    "Powell River, British Columbia, Canada",
    "Saint-Remi, Quebec, Canada",
    "Ottawa, Ontario, Canada",
    "Beaverton, Ontario, Canada",
    "Saint-Roch-de-l'Achigan, Quebec, Canada",
    "Mont-Saint-Hilaire, Quebec, Canada",
    "West Nipissing, Ontario, Canada",
    "Alexandria, Ontario, Canada",
    "Peace River, Alberta, Canada",
    "Shaunavon, Saskatchewan, Canada",
    "Scarborough, Ontario, Canada",
    "Sainte-Anne-des-Monts--Tourelle, Quebec, Canada",
    "Saint Paul, Alberta, Canada",
    "Lac-Brome, Quebec, Canada",
    "Temiscaming, Quebec, Canada",
    "Morrisburg, Ontario, Canada",
    "Kitchener, Ontario, Canada",
    "Souris, Manitoba, Canada",
    "Saint Marys, Ontario, Canada",
    "Carman, Manitoba, Canada",
    "Assiniboia, Saskatchewan, Canada",
    "Saint-Pascal, Quebec, Canada",
    "Saint-Alphonse-de-Granby, Quebec, Canada",
    "Les Cedres, Quebec, Canada",
    "Brighton, Ontario, Canada",
    "Port Colborne, Ontario, Canada",
    "Rocanville, Saskatchewan, Canada",
    "La Baie, Quebec, Canada",
    "Acme, Alberta, Canada",
    "Humboldt, Saskatchewan, Canada",
    "St-Lazare, Manitoba, Canada",
    "Esterhazy, Saskatchewan, Canada",
    "Warwick, Quebec, Canada",
    "Shelburne, Nova Scotia, Canada",
    "Three Hills, Alberta, Canada",
    "Lakeshore, Ontario, Canada",
    "Lantzville, British Columbia, Canada",
    "Mount Albert, Ontario, Canada",
    "Fort Simpson, Northwest Territories, Canada",
    "Shoal Lake, Manitoba, Canada",
    "Fort St. James, British Columbia, Canada",
    "Bluewater, Ontario, Canada",
    "Ste. Agathe, Manitoba, Canada",
    "Sutton, Quebec, Canada",
    "Saint-Pierre, Quebec, Canada",
    "Valcourt, Quebec, Canada",
    "Port Mellon, British Columbia, Canada",
    "Nigadoo, New Brunswick, Canada",
    "Saint-Sylvestre, Quebec, Canada",
    "Lambton, Quebec, Canada",
    "Georgetown, Prince Edward Island, Canada",
    "Deloraine, Manitoba, Canada",
    "Napierville, Quebec, Canada",
    "Fermont, Quebec, Canada",
    "Bonaventure, Quebec, Canada",
    "St-Raymond, Quebec, Canada",
    "Maria, Quebec, Canada",
    "Roxboro, Quebec, Canada",
    "Valcourt, Quebec, Canada",
    "Flin Flon, Manitoba, Canada",
    "Longueuil, Quebec, Canada",
    "Maple Ridge, British Columbia, Canada",
    "Saint-Hubert, Quebec, Canada",
    "North Bay, Ontario, Canada",
    "Burnaby, British Columbia, Canada",
    "Fort St. James, British Columbia, Canada",
    "Elora, Ontario, Canada",
    "Greenfield Park, Quebec, Canada",
    "Grand Valley, Ontario, Canada",
    "Morinville, Alberta, Canada",
    "Nipigon, Ontario, Canada",
    "Picton, Ontario, Canada",
    "Cowansville, Quebec, Canada",
    "Saint-Constant, Quebec, Canada",
    "The Blue Mountains, Ontario, Canada",
    "Dollard-Des Ormeaux, Quebec, Canada",
    "Berthierville, Quebec, Canada",
    "Langdon, Alberta, Canada",
    "Candiac, Quebec, Canada",
    "Sioux Lookout, Ontario, Canada",
    "Sainte-Claire, Quebec, Canada",
    "Austin, Manitoba, Canada",
    "Chapleau, Ontario, Canada",
    "Prince Rupert, British Columbia, Canada",
    "Contrecoeur, Quebec, Canada",
    "St-Croix, Quebec, Canada",
    "La Sarre, Quebec, Canada",
    "Beausejour, Manitoba, Canada",
    "Angus, Ontario, Canada",
    "Barriere, British Columbia, Canada",
    "Fort Nelson, British Columbia, Canada",
    "Renfrew, Ontario, Canada",
    "Acton Vale, Quebec, Canada",
    "Sainte-Marguerite-du-Lac-Masson, Quebec, Canada",
    "Lavaltrie, Quebec, Canada",
    "Arnprior, Ontario, Canada",
    "Pictou, Nova Scotia, Canada",
    "New Richmond, Quebec, Canada",
    "Deseronto, Ontario, Canada",
    "Carignan, Quebec, Canada",
    "Tracadie-Sheila, New Brunswick, Canada",
    "Saint-Hubert, Quebec, Canada",
    "Scott, Quebec, Canada",
    "Sainte-Marguerite-du-Lac-Masson, Quebec, Canada",
    "Saint-Paul, New Brunswick, Canada",
    "Degelis, Quebec, Canada",
    "Les Cedres, Quebec, Canada",
    "Pinawa, Manitoba, Canada",
    "Notre-Dame-du-Bon-Conseil, Quebec, Canada",
    "Temiscaming, Quebec, Canada",
    "Gillam, Manitoba, Canada",
    "Saint-Pierre-de-l'Ile-d'Orleans, Quebec, Canada",
    "Timberlea, Nova Scotia, Canada",
    "Calgary, Alberta, Canada",
    "Saint-Lin-Laurentides, Quebec, Canada",
    "Gananoque, Ontario, Canada",
    "Pincourt, Quebec, Canada",
    "Sundre, Alberta, Canada",
    "Lambton Shores, Ontario, Canada",
    "Dunham, Quebec, Canada",
    "Summerland, British Columbia, Canada",
    "Donnacona, Quebec, Canada",
    "Fall River, Nova Scotia, Canada",
    "Ramara, Ontario, Canada",
    "New Tecumseth, Ontario, Canada",
    "Buffalo Narrows, Saskatchewan, Canada",
    "Espanola, Ontario, Canada",
    "Sainte-Therese, Quebec, Canada",
    "Rothesay, New Brunswick, Canada",
    "Trail, British Columbia, Canada",
    "Gormley, Ontario, Canada",
    "Vaudreuil-Dorion, Quebec, Canada",
    "Colwood, British Columbia, Canada",
    "Deux-Montagnes, Quebec, Canada",
    "Grand Forks, British Columbia, Canada",
    "Becancour, Quebec, Canada",
    "Ponoka, Alberta, Canada",
    "Markdale, Ontario, Canada",
    "Chibougamau, Quebec, Canada",
    "Fort MacLeod, Alberta, Canada",
    "Stonewall, Manitoba, Canada",
    "Embrun, Ontario, Canada",
    "Sainte-Marthe-sur-le-Lac, Quebec, Canada",
    "Sept-Iles, Quebec, Canada",
    "Yamachiche, Quebec, Canada",
    "Digby, Nova Scotia, Canada",
    "Grand Valley, Ontario, Canada",
    "Thorold, Ontario, Canada",
    "Beaconsfield, Quebec, Canada",
    "Portneuf, Quebec, Canada",
    "Ville-Marie, Quebec, Canada",
    "Fairview, Alberta, Canada",
    "Beloeil, Quebec, Canada",
    "Varennes, Quebec, Canada",
    "New Hamburg, Ontario, Canada",
    "Martensville, Saskatchewan, Canada",
    "Bow Island, Alberta, Canada",
    "Canwood, Saskatchewan, Canada",
    "Pincourt, Quebec, Canada",
    "La Loche, Saskatchewan, Canada",
    "Treherne, Manitoba, Canada",
    "Burgessville, Ontario, Canada",
    "Elie, Manitoba, Canada",
    "Laurier-Station, Quebec, Canada",
    "Saint-Quentin, New Brunswick, Canada",
    "Eston, Saskatchewan, Canada",
    "Gimli, Manitoba, Canada",
    "Grenville, Quebec, Canada",
    "Balcarres, Saskatchewan, Canada",
    "Muenster, Saskatchewan, Canada",
    "Amqui, Quebec, Canada",
    "Vancouver, British Columbia, Canada",
    "Hanley, Saskatchewan, Canada",
    "Wilcox, Saskatchewan, Canada",
    "Saint-Felix-de-Valois, Quebec, Canada",
    "Lac du Bonnet, Manitoba, Canada",
    "Lorette, Manitoba, Canada",
    "Weekes, Saskatchewan, Canada",
    "Prevost, Quebec, Canada",
    "Montreal, Quebec, Canada",
    "Ottawa, Ontario, Canada",
    "Brockville, Ontario, Canada",
    "Halifax, Nova Scotia, Canada",
    "Greater Sudbury, Ontario, Canada",
    "Fredericton, New Brunswick, Canada",
    "Inuvik, Northwest Territories, Canada",
    "Penticton, British Columbia, Canada",
    "Fort Erie, Ontario, Canada",
    "Quebec City, Quebec, Canada",
    "Laval, Quebec, Canada",
    "Winnipeg, Manitoba, Canada",
    "Regina, Saskatchewan, Canada",
    "Calgary, Alberta, Canada",
    "Yellowknife, Northwest Territories, Canada",
    "Waterloo, Ontario, Canada",
    "Mirabel, Quebec, Canada",
    "Beloeil, Quebec, Canada",
    "Nanaimo, British Columbia, Canada",
    "Sorel-Tracy, Quebec, Canada",
    "Montmagny, Quebec, Canada",
    "Delta, British Columbia, Canada",
    "Mount Royal, Quebec, Canada",
    "Maple Creek, Saskatchewan, Canada",
    "Leamington, Ontario, Canada",
    "La Malbaie, Quebec, Canada",
    "Airdrie, Alberta, Canada",
    "Baie-Saint-Paul, Quebec, Canada",
    "Greater Sudbury, Ontario, Canada",
    "Langley City, British Columbia, Canada",
    "New Westminster, British Columbia, Canada",
    "Dawson Creek, British Columbia, Canada",
    "Osoyoos, British Columbia, Canada",
    "Lacombe, Alberta, Canada",
    "Antigonish, Nova Scotia, Canada",
    "Dartmouth, Nova Scotia, Canada",
    "Windsor, Nova Scotia, Canada",
    "Duncan, British Columbia, Canada",
    "Squamish, British Columbia, Canada",
    "Barrie, Ontario, Canada",
    "Okotoks, Alberta, Canada",
    "Langley City, British Columbia, Canada",
    "Amherstburg, Ontario, Canada",
    "Grand Falls-Windsor, Newfoundland and Labrador, Canada",
    "Sicamous, British Columbia, Canada",
    "Charlottetown, Prince Edward Island, Canada",
    "Gander, Newfoundland and Labrador, Canada",
    "Saugeen Shores, Ontario, Canada",
    "Belleville, Ontario, Canada",
    "Slave Lake, Alberta, Canada",
    "Sainte-Catherine-de-la-Jacques-Cartier, Quebec, Canada",
    "Saint-Sauveur, Quebec, Canada",
    "Mount Royal, Quebec, Canada",
    "Oshawa, Ontario, Canada",
    "Sarnia, Ontario, Canada",
    "Georgetown, Ontario, Canada",
    "St-Bruno-de-Montarville, Quebec, Canada",
    "Kemptville, Ontario, Canada",
    "Sherwood Park, Alberta, Canada",
    "Farnham, Quebec, Canada",
    "Riviere-du-Loup, Quebec, Canada",
    "Owen Sound, Ontario, Canada",
    "Port Moody, British Columbia, Canada",
    "Campbell River, British Columbia, Canada",
    "Cornwall, Ontario, Canada",
    "Brandon, Manitoba, Canada",
    "Saint-Cesaire, Quebec, Canada",
    "Bowmanville, Ontario, Canada",
    "Brantford, Ontario, Canada",
    "Niagara Falls, Ontario, Canada",
    "Whitchurch-Stouffville, Ontario, Canada",
    "Edson, Alberta, Canada",
    "Bradford West Gwillimbury, Ontario, Canada",
    "Mission, British Columbia, Canada",
    "100 Mile House, British Columbia, Canada",
    "Deschambault, Quebec, Canada",
    "LaSalle, Ontario, Canada",
    "Whitewood, Saskatchewan, Canada",
    "Vermilion, Alberta, Canada",
    "Rosemere, Quebec, Canada",
    "Saint-Louis de Kent, New Brunswick, Canada",
    "Didsbury, Alberta, Canada",
    "Edmundston, New Brunswick, Canada",
    "Ayr, Ontario, Canada",
    "West Vancouver, British Columbia, Canada",
    "Bedford, Nova Scotia, Canada",
    "Indian Head, Saskatchewan, Canada",
    "Lakefield, Ontario, Canada",
    "Clearwater, British Columbia, Canada",
    "Brant, Ontario, Canada",
    "St. Albert, Alberta, Canada",
    "Mount Royal, Quebec, Canada",
    "Tillsonburg, Ontario, Canada",
    "Amos, Quebec, Canada",
    "Bois-des-Filion, Quebec, Canada",
    "Saint-Hyacinthe, Quebec, Canada",
    "Rimbey, Alberta, Canada",
    "Atholville, New Brunswick, Canada",
    "Goderich, Ontario, Canada",
    "Temiskaming Shores, Ontario, Canada",
    "Levis, Quebec, Canada",
    "Bridgewater, Nova Scotia, Canada",
    "Huntsville, Ontario, Canada",
    "Swift Current, Saskatchewan, Canada",
    "Richelieu, Quebec, Canada",
    "Papineauville, Quebec, Canada",
    "Elliot Lake, Ontario, Canada",
    "Saint-Nicolas, Quebec, Canada",
    "Brooks, Alberta, Canada",
    "Blainville, Quebec, Canada",
    "Provost, Alberta, Canada",
    "Bedford, Quebec, Canada",
    "Kitimat, British Columbia, Canada",
    "Alma, Quebec, Canada",
    "Haldimand, Ontario, Canada",
    "Kirkland, Quebec, Canada",
    "Outlook, Saskatchewan, Canada",
    "Ladysmith, British Columbia, Canada",
    "Schomberg, Ontario, Canada",
    "Wilkie, Saskatchewan, Canada",
    "Stettler, Alberta, Canada",
    "The Blue Mountains, Ontario, Canada",
    "Mont-Joli, Quebec, Canada",
    "Fort St. John, British Columbia, Canada",
    "Acton, Ontario, Canada",
    "Morris, Manitoba, Canada",
    "Carberry, Manitoba, Canada",
    "Paradise, Newfoundland and Labrador, Canada",
    "Blind River, Ontario, Canada",
    "Cayuga, Ontario, Canada",
    "Redcliff, Alberta, Canada",
    "Waterford, Ontario, Canada",
    "Berwick, Nova Scotia, Canada",
    "Windsor, Quebec, Canada",
    "Chase, British Columbia, Canada",
    "St. Albert, Alberta, Canada",
    "Asbestos, Quebec, Canada",
    "Big River, Saskatchewan, Canada",
    "Beauceville, Quebec, Canada",
    "Bamfield, British Columbia, Canada",
    "Pont-Rouge, Quebec, Canada",
    "Eastern Passage, Nova Scotia, Canada",
    "Rimouski, Quebec, Canada",
    "Saint-Lambert, Quebec, Canada",
    "Burlington, Ontario, Canada",
    "Cowansville, Quebec, Canada",
    "Fort McMurray, Alberta, Canada",
    "Cranbrook, British Columbia, Canada",
    "Sparwood, British Columbia, Canada",
    "Richmond, British Columbia, Canada",
    "Alma, Quebec, Canada",
    "Banff, Alberta, Canada",
    "Prince George, British Columbia, Canada",
    "Shawinigan, Quebec, Canada",
    "Lethbridge, Alberta, Canada",
    "London, Ontario, Canada",
    "Aurora, Ontario, Canada",
    "Red Deer, Alberta, Canada",
    "Bromont, Quebec, Canada",
    "Mattawa, Ontario, Canada",
    "Windsor, Ontario, Canada",
    "Trois-Rivieres, Quebec, Canada",
    "Courtice, Ontario, Canada",
    "Newmarket, Ontario, Canada",
    "Westmount, Quebec, Canada",
    "Ajax, Ontario, Canada",
    "Saint-Jean-sur-Richelieu, Quebec, Canada",
    "Granby, Quebec, Canada",
    "Sainte-Marie, Quebec, Canada",
    "Chateauguay, Quebec, Canada",
    "L'Ancienne-Lorette, Quebec, Canada",
    "Vanderhoof, British Columbia, Canada",
    "Leduc, Alberta, Canada",
    "Sidney, British Columbia, Canada",
    "Truro, Nova Scotia, Canada",
    "Grande Prairie, Alberta, Canada",
    "Fort St. John, British Columbia, Canada",
    "Quebec City, Quebec, Canada",
    "Papineauville, Quebec, Canada",
    "Rimouski, Quebec, Canada",
    "Burns Lake, British Columbia, Canada",
    "Pointe-Claire, Quebec, Canada",
    "Moose Jaw, Saskatchewan, Canada",
    "North Battleford, Saskatchewan, Canada",
    "Tecumseh, Ontario, Canada",
    "Amos, Quebec, Canada",
    "Yarmouth, Nova Scotia, Canada",
    "Prince Albert, Saskatchewan, Canada",
    "Port Perry, Ontario, Canada",
    "Dollard-Des Ormeaux, Quebec, Canada",
    "Val-d'Or, Quebec, Canada",
    "Fort Frances, Ontario, Canada",
    "Maniwaki, Quebec, Canada",
    "Mont-Laurier, Quebec, Canada",
    "Gatineau, Quebec, Canada",
    "Trois-Rivieres, Quebec, Canada",
    "New Minas, Nova Scotia, Canada",
    "Blainville, Quebec, Canada",
    "La Prairie, Quebec, Canada",
    "St. John's, Newfoundland and Labrador, Canada",
    "Kentville, Nova Scotia, Canada",
    "Dolbeau-Mistassini, Quebec, Canada",
    "Perth, Ontario, Canada",
    "Williams Lake, British Columbia, Canada",
    "Dollard-Des Ormeaux, Quebec, Canada",
    "Bracebridge, Ontario, Canada",
    "Gravenhurst, Ontario, Canada",
    "Saint-Lin-Laurentides, Quebec, Canada",
    "Canmore, Alberta, Canada",
    "Saint-Felix-de-Valois, Quebec, Canada",
    "Saint-Jean-sur-Richelieu, Quebec, Canada",
    "Nelson, British Columbia, Canada",
    "Port Hope, Ontario, Canada",
    "Sussex, New Brunswick, Canada",
    "Sydney, Nova Scotia, Canada",
    "Sainte-Catherine, Quebec, Canada",
    "Thornhill, Ontario, Canada",
    "Kaslo, British Columbia, Canada",
    "Roberval, Quebec, Canada",
    "Chatham-Kent, Ontario, Canada",
    "Innisfil, Ontario, Canada",
    "Delson, Quebec, Canada",
    "Sault Ste. Marie, Ontario, Canada",
    "Whitecourt, Alberta, Canada",
    "Rocky Mountain House, Alberta, Canada",
    "Woodstock, New Brunswick, Canada",
    "Saint Marys, Ontario, Canada",
    "Rosetown, Saskatchewan, Canada",
    "Terrace, British Columbia, Canada",
    "Wainwright, Alberta, Canada",
    "Labrador City, Newfoundland and Labrador, Canada",
    "Sainte-Agathe-des-Monts, Quebec, Canada",
    "Port Hardy, British Columbia, Canada",
    "Dollard-Des Ormeaux, Quebec, Canada",
    "Sainte-Adele, Quebec, Canada",
    "Sainte-Marthe-sur-le-Lac, Quebec, Canada",
    "Elmira, Ontario, Canada",
    "Kawartha Lakes, Ontario, Canada",
    "Prevost, Quebec, Canada",
    "Cobden, Ontario, Canada",
    "St-Bruno-de-Montarville, Quebec, Canada",
    "Terrace Bay, Ontario, Canada",
    "Baie-Comeau, Quebec, Canada",
    "Sorel-Tracy, Quebec, Canada",
    "Prince Edward, Ontario, Canada",
    "Richelieu, Quebec, Canada",
    "Boischatel, Quebec, Canada",
    "Clinton, British Columbia, Canada",
    "Clinton, Ontario, Canada",
    "Iroquois Falls, Ontario, Canada",
    "Winkler, Manitoba, Canada",
    "Nicolet, Quebec, Canada",
    "Lambton, Quebec, Canada",
    "Val-Morin, Quebec, Canada",
    "Lac-Megantic, Quebec, Canada",
    "Sheet Harbour, Nova Scotia, Canada",
    "Juniper, New Brunswick, Canada",
    "Saint Paul, Alberta, Canada",
    "Brentwood Bay, British Columbia, Canada",
    "Orleans, Ontario, Canada",
    "Kuujjuaq, Quebec, Canada",
    "Magog, Quebec, Canada",
    "Wainfleet, Ontario, Canada",
    "North Sydney, Nova Scotia, Canada",
    "Manitou, Manitoba, Canada",
    "Minto, Ontario, Canada",
    "Manitouwadge, Ontario, Canada",
    "Barwick, Ontario, Canada",
    "Salt Spring Island, British Columbia, Canada",
    "Plympton-Wyoming, Ontario, Canada",
    "Gaspe, Quebec, Canada",
    "Sainte-Julie, Quebec, Canada",
    "Tees, Alberta, Canada",
    "Tofield, Alberta, Canada",
    "Arborg, Manitoba, Canada",
    "Sainte-Anne-de-Bellevue, Quebec, Canada",
    "Trois-Pistoles, Quebec, Canada",
    "Burk's Falls, Ontario, Canada",
    "Saint-Alphonse-de-Granby, Quebec, Canada",
    "Haley Station, Ontario, Canada",
    "Saint-Sylvestre, Quebec, Canada",
    "Marieville, Quebec, Canada",
    "Doaktown, New Brunswick, Canada",
    "Naramata, British Columbia, Canada",
    "Kouchibouguac National Park, New Brunswick, Canada",
    "North York, Ontario, Canada",
    "Dugald, Manitoba, Canada",
    "Barrington, Nova Scotia, Canada",
    "Selwyn, Ontario, Canada",
    "York, Ontario, Canada",
    "Point Edward, Ontario, Canada",
    "Midhurst, Ontario, Canada",
    "Boissevain, Manitoba, Canada",
    "Smithers, British Columbia, Canada",
    "Radville, Saskatchewan, Canada",
    "Shippagan, New Brunswick, Canada",
    "Dawson City, Yukon, Canada",
    "Stanstead, Quebec, Canada",
    "Glenboro, Manitoba, Canada",
    "Taber, Alberta, Canada",
    "Ucluelet, British Columbia, Canada",
    "Ingersoll, Ontario, Canada",
    "Iqaluit, Nunavut, Canada",
    "Madoc, Ontario, Canada",
    "Saint-Pie, Quebec, Canada",
    "Kirkland, Quebec, Canada",
    "Saint-Roch-de-l'Achigan, Quebec, Canada",
    "Warman, Saskatchewan, Canada",
    "Shawnigan Lake, British Columbia, Canada",
    "Mackenzie, British Columbia, Canada",
    "Matachewan, Ontario, Canada",
    "Allan, Saskatchewan, Canada",
    "Colborne, Ontario, Canada",
    "High Prairie, Alberta, Canada",
    "Sainte-Claire, Quebec, Canada",
    "Waterloo, Quebec, Canada",
    "Selkirk, Manitoba, Canada",
    "Piedmont, Quebec, Canada",
    "L'Ancienne-Lorette, Quebec, Canada",
    "Griffin, Saskatchewan, Canada",
    "Beaupre, Quebec, Canada",
    "Lakefield, Ontario, Canada",
    "Moosomin, Saskatchewan, Canada",
    "Temiscouata-sur-le-Lac, Quebec, Canada",
    "Wolfville, Nova Scotia, Canada",
    "Farnham, Quebec, Canada",
    "Baie Verte, Newfoundland and Labrador, Canada",
    "Greater Napanee, Ontario, Canada",
    "Wynyard, Saskatchewan, Canada",
    "North Portal, Saskatchewan, Canada",
    "Lasalle, Quebec, Canada",
    "Powassan, Ontario, Canada",
    "South Slocan, British Columbia, Canada",
    "Cambridge Bay, Nunavut, Canada",
    "Minnedosa, Manitoba, Canada",
    "Dunham, Quebec, Canada",
    "L'Orignal, Ontario, Canada",
    "Fort St. James, British Columbia, Canada",
    "Smooth Rock Falls, Ontario, Canada",
    "Hudson, Quebec, Canada",
    "Dorset, Ontario, Canada",
    "Oliver, British Columbia, Canada",
    "Baie-D'Urfe, Quebec, Canada",
    "Cote Saint-Luc, Quebec, Canada",
    "Kingsville, Ontario, Canada",
    "Cobourg, Ontario, Canada",
    "Fernie, British Columbia, Canada",
    "Russell, Manitoba, Canada",
    "St-Croix, Quebec, Canada",
    "Lac la Biche, Alberta, Canada",
    "Sainte-Julie, Quebec, Canada",
    "Thetford Mines, Quebec, Canada",
    "Quispamsis, New Brunswick, Canada",
    "Port Hawkesbury, Nova Scotia, Canada",
    "Mont-Laurier, Quebec, Canada",
    "Chicoutimi, Quebec, Canada",
    "L'Assomption, Quebec, Canada",
    "St-Bruno-de-Montarville, Quebec, Canada",
    "Beaconsfield, Quebec, Canada",
    "Quesnel, British Columbia, Canada",
    "Thompson, Manitoba, Canada",
    "Listowel, Ontario, Canada",
    "Kapuskasing, Ontario, Canada",
    "Matane, Quebec, Canada",
    "Marathon, Ontario, Canada",
    "Sept-Iles, Quebec, Canada",
    "Shippagan, New Brunswick, Canada",
    "McBride, British Columbia, Canada",
    "Vegreville, Alberta, Canada",
    "Sainte-Anne-des-Plaines, Quebec, Canada",
    "Port McNicoll, Ontario, Canada",
    "Ashcroft, British Columbia, Canada",
    "La Pocatiere, Quebec, Canada",
    "Boisbriand, Quebec, Canada",
    "King City, Ontario, Canada",
    "Milverton, Ontario, Canada",
    "Castlegar, British Columbia, Canada",
    "Waterville, Quebec, Canada",
    "Hawkesbury, Ontario, Canada",
    "Sainte-Adele, Quebec, Canada",
    "Becancour, Quebec, Canada",
    "Crowsnest Pass, Alberta, Canada",
    "Drayton Valley, Alberta, Canada",
    "Lloydminster, Alberta, Canada",
    "Wabush, Newfoundland and Labrador, Canada",
    "Shelburne, Ontario, Canada",
    "La Prairie, Quebec, Canada",
    "Dubreuilville, Ontario, Canada",
    "Melville, Saskatchewan, Canada",
    "Hanna, Alberta, Canada",
    "Gull Lake, Saskatchewan, Canada",
    "Princeton, British Columbia, Canada",
    "Caronport, Saskatchewan, Canada",
    "Beausejour, Manitoba, Canada",
    "Penetanguishene, Ontario, Canada",
    "Chateau-Richer, Quebec, Canada",
    "Ashern, Manitoba, Canada",
    "Norquay, Saskatchewan, Canada",
    "West Nipissing, Ontario, Canada",
    "Arva, Ontario, Canada",
    "Huron East, Ontario, Canada",
    "Berthierville, Quebec, Canada",
    "Hubbards, Nova Scotia, Canada",
    "Beaupre, Quebec, Canada",
    "Brome, Quebec, Canada",
    "Deux-Montagnes, Quebec, Canada",
    "Dundurn, Saskatchewan, Canada",
    "Apsley, Ontario, Canada",
    "Lombardy, Ontario, Canada",
    "Creighton, Saskatchewan, Canada",
    "Lumby, British Columbia, Canada",
    "Mahone Bay, Nova Scotia, Canada",
    "Fort Saskatchewan, Alberta, Canada",
    "Erin, Ontario, Canada",
    "Rankin Inlet, Nunavut, Canada",
    "Saint-Joseph-de-Beauce, Quebec, Canada",
    "Powerview-Pine Falls, Manitoba, Canada",
    "Scott, Quebec, Canada",
    "Vallee-Jonction, Quebec, Canada",
    "Grande Cache, Alberta, Canada",
    "Lac-Megantic, Quebec, Canada",
    "Oromocto, New Brunswick, Canada",
    "North Saanich, British Columbia, Canada",
    "Richmond, Quebec, Canada",
    "Norwich, Ontario, Canada",
    "Sackville, New Brunswick, Canada",
    "Thetford Mines, Quebec, Canada",
    "Montmagny, Quebec, Canada",
    "Ile-a-la-Crosse, Saskatchewan, Canada",
    "Kimberley, British Columbia, Canada",
    "Dawson City, Yukon, Canada",
    "Lac-Brome, Quebec, Canada",
    "Creemore, Ontario, Canada",
    "Piedmont, Quebec, Canada",
    "Athabasca, Alberta, Canada",
    "Bouctouche, New Brunswick, Canada",
    "Halton Hills, Ontario, Canada",
    "Nobleton, Ontario, Canada",
    "Earlton, Ontario, Canada",
    "Shellbrook, Saskatchewan, Canada",
    "Coldwater, Ontario, Canada",
    "Baker Lake, Nunavut, Canada",
    "Laurier-Station, Quebec, Canada",
    "Gravelbourg, Saskatchewan, Canada",
    "Baie-D'Urfe, Quebec, Canada",
    "Lorraine, Quebec, Canada",
    "Wawanesa, Manitoba, Canada",
    "Moose Creek, Ontario, Canada",
    "Eastman, Quebec, Canada",
    "Smithville, Ontario, Canada",
    "Rexton, New Brunswick, Canada",
    "Onanole, Manitoba, Canada",
    "Bois-des-Filion, Quebec, Canada",
    "L'Assomption, Quebec, Canada",
    "Teulon, Manitoba, Canada",
    "Bois-des-Filion, Quebec, Canada",
    "Tignish, Prince Edward Island, Canada",
    "Rainy River, Ontario, Canada",
    "Waterloo, Quebec, Canada",
    "Carleton-sur-mer, Quebec, Canada",
    "Ramara, Ontario, Canada",
    "Killarney, Manitoba, Canada",
    "Richmond, Ontario, Canada",
    "Gold River, British Columbia, Canada",
    "Kahnawake, Quebec, Canada",
    "Glencoe, Ontario, Canada",
    "Mont-Joli, Quebec, Canada",
    "Contrecoeur, Quebec, Canada",
    "Springdale, Newfoundland and Labrador, Canada",
    "St. Jacobs, Ontario, Canada",
    "Temiscouata-sur-le-Lac, Quebec, Canada",
    "Lac-Etchemin, Quebec, Canada",
    "Saint-Basile-le-Grand, Quebec, Canada",
    "Stanstead, Quebec, Canada",
    "Campbellford, Ontario, Canada",
    "Valemount, British Columbia, Canada",
    "Montebello, Quebec, Canada",
    "Whistler, British Columbia, Canada",
    "Wetaskiwin, Alberta, Canada",
    "Lachute, Quebec, Canada",
    "Edmundston, New Brunswick, Canada",
    "Hearst, Ontario, Canada",
    "Beaumont, Alberta, Canada",
    "Shediac, New Brunswick, Canada",
    "Acton Vale, Quebec, Canada",
    "St. Thomas, Ontario, Canada",
    "Saint-Georges, Quebec, Canada",
    "Sainte-Agathe-des-Monts, Quebec, Canada",
    "Saint-Basile-le-Grand, Quebec, Canada",
    "Lindsay, Ontario, Canada",
    "Rouyn-Noranda, Quebec, Canada",
    "Stony Plain, Alberta, Canada",
    "Estevan, Saskatchewan, Canada",
    "Bonnyville, Alberta, Canada",
    "Gaspe, Quebec, Canada",
    "Chambly, Quebec, Canada",
    "Pangnirtung, Nunavut, Canada",
    "L'Ile-Perrot, Quebec, Canada",
    "Saint-Pie, Quebec, Canada",
    "Mill Bay, British Columbia, Canada",
    "Hudson Bay, Saskatchewan, Canada",
    "Danville, Quebec, Canada",
    "Saint-Basile-le-Grand, Quebec, Canada",
    "Pont-Rouge, Quebec, Canada",
    "Newcastle, Ontario, Canada",
    "Saint-Augustin, Quebec, Canada",
    "Steinbach, Manitoba, Canada",
    "Edam, Saskatchewan, Canada",
    "Bancroft, Ontario, Canada",
    "New Richmond, Quebec, Canada",
    "Miami, Manitoba, Canada",
    "Saint-Felicien, Quebec, Canada",
    "Fisher Branch, Manitoba, Canada",
    "Rosemere, Quebec, Canada",
    "Lake Cowichan, British Columbia, Canada",
    "Saint-Mathieu-de-Beloeil, Quebec, Canada",
    "Dorval, Quebec, Canada",
    "Memramcook, New Brunswick, Canada",
    "Clair, New Brunswick, Canada",
    "Saint-Pierre-de-l'Ile-d'Orleans, Quebec, Canada",
    "Saint-Cyrille-de-Wendover, Quebec, Canada",
    "Lutselk'e, Northwest Territories, Canada",
    "Amqui, Quebec, Canada",
    "Montreal, Quebec, Canada",
    "Durham, Ontario, Canada",
    "Carlisle, Ontario, Canada",
    "Saint-Elzear, Quebec, Canada",
    "L'Epiphanie, Quebec, Canada",
    "La Pocatiere, Quebec, Canada",
    "Red Lake, Ontario, Canada",
    "Merrickville-Wolford, Ontario, Canada",
    "Russell, Ontario, Canada",
    "Degelis, Quebec, Canada",
    "View Royal, British Columbia, Canada",
    "Oak Bluff, Manitoba, Canada",
    "Waterton Lakes National Park of Canada, Alberta, Canada",
    "McCreary, Manitoba, Canada",
    "Richibucto Road, New Brunswick, Canada",
    "Frontier, Saskatchewan, Canada",
    "Saint-Laurent, Quebec, Canada",
    "Saint-Boniface-de-Shawinigan, Quebec, Canada",
    "Portneuf, Quebec, Canada",
    "Bonshaw, Prince Edward Island, Canada",
    "Nigadoo, New Brunswick, Canada",
    "Saint-Victor, Quebec, Canada",
    "Abbotsford, British Columbia, Canada",
    "Vancouver, British Columbia, Canada",
    "Toronto, Ontario, Canada",
    "Sherbrooke, Quebec, Canada",
    "Kelowna, British Columbia, Canada",
    "Cambridge, Ontario, Canada",
    "Saint John, New Brunswick, Canada",
    "St. Catharines, Ontario, Canada",
    "Brampton, Ontario, Canada",
    "Saguenay, Quebec, Canada",
    "Moncton, New Brunswick, Canada",
    "Levis, Quebec, Canada",
    "Notre-Dame-du-Bon-Conseil, Quebec, Canada",
    "Lillooet, British Columbia, Canada",
    "Happy Valley-Goose Bay, Newfoundland and Labrador, Canada",
    "Hamilton, Ontario, Canada",
    "St-Bruno-de-Montarville, Quebec, Canada",
    "Gatineau, Quebec, Canada",
    "Welland, Ontario, Canada",
    "Chambly, Quebec, Canada",
    "Quebec City, Quebec, Canada",
    "St. John's, Newfoundland and Labrador, Canada",
    "Quebec City, Quebec, Canada",
    "Thunder Bay, Ontario, Canada",
    "Saint-Eustache, Quebec, Canada",
    "Etobicoke, Ontario, Canada",
    "Florenceville-Bristol, New Brunswick, Canada",
    "Milton, Ontario, Canada",
    "Saskatoon, Saskatchewan, Canada",
    "Montreal, Quebec, Canada",
    "Coquitlam, British Columbia, Canada",
    "Whitehorse, Yukon, Canada",
    "Tracadie-Sheila, New Brunswick, Canada",
    "Kincardine, Ontario, Canada",
    "Langley Township, British Columbia, Canada",
    "Drummondville, Quebec, Canada",
    "Collingwood, Ontario, Canada",
    "White Rock, British Columbia, Canada",
    "Dieppe, New Brunswick, Canada",
    "La Tuque, Quebec, Canada",
    "Merritt, British Columbia, Canada",
    "Valleyview, Alberta, Canada",
    "Orillia, Ontario, Canada",
    "Caledon, Ontario, Canada",
    "Spruce Grove, Alberta, Canada",
    "Carignan, Quebec, Canada",
    "Hinton, Alberta, Canada",
    "Courtenay, British Columbia, Canada",
    "Bathurst, New Brunswick, Canada",
    "Fort Saskatchewan, Alberta, Canada",
    "Dorval, Quebec, Canada",
    "Greater Napanee, Ontario, Canada",
    "Cumberland, British Columbia, Canada",
    "Whitby, Ontario, Canada",
    "Ste. Anne, Manitoba, Canada",
    "Cold Lake, Alberta, Canada",
    "Pitt Meadows, British Columbia, Canada",
    "Haliburton, Ontario, Canada",
    "Asbestos, Quebec, Canada",
    "Joliette, Quebec, Canada",
    "Carleton Place, Ontario, Canada",
    "Pembroke, Ontario, Canada",
    "Woodstock, Ontario, Canada",
    "Salaberry-de-Valleyfield, Quebec, Canada",
    "Strathroy, Ontario, Canada",
    "Saint-Martin, Quebec, Canada",
    "Smiths Falls, Ontario, Canada",
    "Richibucto, New Brunswick, Canada",
    "Shawinigan, Quebec, Canada",
    "Masset, British Columbia, Canada",
    "Nipawin, Saskatchewan, Canada",
    "Nisku, Alberta, Canada",
    "Kingsey Falls, Quebec, Canada",
    "Petawawa, Ontario, Canada",
    "Saint-Alphonse-de-Granby, Quebec, Canada",
    "Saint-Anselme, Quebec, Canada",
    "Georgina, Ontario, Canada",
    "Saint-Augustin, Quebec, Canada",
    "Orangeville, Ontario, Canada",
    "Enfield, Nova Scotia, Canada",
    "Melfort, Saskatchewan, Canada",
    "Varennes, Quebec, Canada",
    "Amherst, Nova Scotia, Canada",
    "Terrebonne, Quebec, Canada",
    "Olds, Alberta, Canada",
    "St-Raymond, Quebec, Canada",
    "Grimsby, Ontario, Canada",
    "Sainte-Catherine-de-la-Jacques-Cartier, Quebec, Canada",
    "Camrose, Alberta, Canada",
    "Nicolet, Quebec, Canada",
    "Salmon Arm, British Columbia, Canada",
    "Miramichi, New Brunswick, Canada",
    "Clarenville, Newfoundland and Labrador, Canada",
    "Westmount, Quebec, Canada",
    "Sorel-Tracy, Quebec, Canada",
    "St-Bruno-de-Montarville, Quebec, Canada",
    "Baie-D'Urfe, Quebec, Canada",
    "Lanark, Ontario, Canada",
    "Quebec City, Quebec, Canada",
    "Parry Sound, Ontario, Canada",
    "St-Tite, Quebec, Canada",
    "Deep River, Ontario, Canada",
    "Barrhead, Alberta, Canada",
    "Golden, British Columbia, Canada",
    "Altona, Manitoba, Canada",
    "Hay River, Northwest Territories, Canada",
    "Saint-Sauveur, Quebec, Canada",
    "Coaticook, Quebec, Canada",
    "Sainte-Therese, Quebec, Canada",
    "Richmond, Quebec, Canada",
    "Blue River, British Columbia, Canada",
    "Chestermere, Alberta, Canada",
    "Stephenville, Newfoundland and Labrador, Canada",
    "Matane, Quebec, Canada",
    "Port-Cartier, Quebec, Canada",
    "Dryden, Ontario, Canada",
    "Portage la Prairie, Manitoba, Canada",
    "Hope, British Columbia, Canada",
    "Louiseville, Quebec, Canada",
    "Niverville, Manitoba, Canada",
    "Kamsack, Saskatchewan, Canada",
    "Swan River, Manitoba, Canada",
    "Saint-Remi, Quebec, Canada",
    "Fillmore, Saskatchewan, Canada",
    "St. Jacobs, Ontario, Canada",
    "Carlyle, Saskatchewan, Canada",
    "Mercier, Quebec, Canada",
    "Cole Harbour, Nova Scotia, Canada",
    "New Dundee, Ontario, Canada",
    "Port-Cartier, Quebec, Canada",
    "Sainte-Agathe-de-Lotbiniere, Quebec, Canada",
    "Saint Stephen, New Brunswick, Canada",
    "Millbrook, Ontario, Canada",
    "Hudson, Quebec, Canada",
    "Cochrane, Ontario, Canada",
    "Prince Albert National Park, Saskatchewan, Canada",
    "South River, Ontario, Canada",
    "Edmonton International Airport, Alberta, Canada",
    "Queen Charlotte, British Columbia, Canada",
    "Barry's Bay, Ontario, Canada",
    "Cranberry Portage, Manitoba, Canada",
    "Saint John, New Brunswick, Canada",
    "Saint-Victor, Quebec, Canada",
    "Selwyn, Ontario, Canada",
    "Goffs, Nova Scotia, Canada",
    "Lasalle, Quebec, Canada",
    "Mississauga, Ontario, Canada",
    "Salaberry-de-Valleyfield, Quebec, Canada",
    "Lundar, Manitoba, Canada",
    "Perce, Quebec, Canada",
    "Canyon, British Columbia, Canada",
    "Roberval, Quebec, Canada",
    "Vankleek Hill, Ontario, Canada",
    "LeMoyne, Quebec, Canada",
    "Berthierville, Quebec, Canada",
    "Chateau-Richer, Quebec, Canada",
    "Danville, Quebec, Canada",
    "Snow Lake, Manitoba, Canada",
    "Victoria, British Columbia, Canada",
    "Langley Township, British Columbia, Canada",
    "Medicine Hat, Alberta, Canada",
    "Westlock, Alberta, Canada",
    "Edmonton, Alberta, Canada",
    "Quebec City, Quebec, Canada",
    "Vaughan, Ontario, Canada",
    "Mississauga, Ontario, Canada",
    "Kingston, Ontario, Canada",
    "Surrey, British Columbia, Canada",
    "Brossard, Quebec, Canada",
    "North Vancouver, British Columbia, Canada",
    "Terrebonne, Quebec, Canada",
    "Victoriaville, Quebec, Canada",
    "Markham, Ontario, Canada",
    "Saint-Hyacinthe, Quebec, Canada",
    "New Glasgow, Nova Scotia, Canada",
    "Oakville, Ontario, Canada",
    "Port Coquitlam, British Columbia, Canada",
    "Pickering, Ontario, Canada",
    "Boucherville, Quebec, Canada",
    "Kamloops, British Columbia, Canada",
    "Guelph, Ontario, Canada",
    "Hanover, Ontario, Canada",
    "Vernon, British Columbia, Canada",
    "Comox, British Columbia, Canada",
    "Rouyn-Noranda, Quebec, Canada",
    "Richmond Hill, Ontario, Canada",
    "Quinte West, Ontario, Canada",
    "Chalk River, Ontario, Canada",
    "Mont-Tremblant, Quebec, Canada",
    "Chilliwack, British Columbia, Canada",
    "Kitchener, Ontario, Canada",
    "Boisbriand, Quebec, Canada",
    "Revelstoke, British Columbia, Canada",
    "Pointe-Claire, Quebec, Canada",
    "High Level, Alberta, Canada",
    "Lower Sackville, Nova Scotia, Canada",
    "Pincher Creek, Alberta, Canada",
    "Saint-Mathieu-de-Beloeil, Quebec, Canada",
    "Chateauguay, Quebec, Canada",
    "Clarence-Rockland, Ontario, Canada",
    "Drumheller, Alberta, Canada",
    "Meadow Lake, Saskatchewan, Canada",
    "Niagara-on-the-Lake, Ontario, Canada",
    "Stoney Creek, Ontario, Canada",
    "Brossard, Quebec, Canada",
    "Mascouche, Quebec, Canada",
    "Stratford, Ontario, Canada",
    "Timmins, Ontario, Canada",
    "Saint-Georges, Quebec, Canada",
    "Vaudreuil-Dorion, Quebec, Canada",
    "Yorkton, Saskatchewan, Canada",
    "Kindersley, Saskatchewan, Canada",
    "Casselman, Ontario, Canada",
    "Boucherville, Quebec, Canada",
    "Ripley, Ontario, Canada",
    "Saint Leonard, Quebec, Canada",
    "Summerside, Prince Edward Island, Canada",
    "Moosonee, Ontario, Canada",
    "St. Thomas, Ontario, Canada",
    "Saint-Jerome, Quebec, Canada",
    "Lloydminster, Alberta, Canada",
    "Saint-Jean-de-l'Ile-d'Orleans, Quebec, Canada",
    "Sainte-Marie, Quebec, Canada",
    "Magog, Quebec, Canada",
    "Peterborough, Ontario, Canada",
    "Jasper, Alberta, Canada",
    "Fergus, Ontario, Canada",
    "Parksville, British Columbia, Canada",
    "Saint-Nicolas, Quebec, Canada",
    "Mercier, Quebec, Canada",
    "Port Alberni, British Columbia, Canada",
    "Norman Wells, Northwest Territories, Canada",
    "Aylmer, Ontario, Canada",
    "Sylvan Lake, Alberta, Canada",
    "Stellarton, Nova Scotia, Canada",
    "The Pas, Manitoba, Canada",
    "Saint-Quentin, New Brunswick, Canada",
    "Campbellton, New Brunswick, Canada",
    "Saint-Lambert, Quebec, Canada",
    "Pohenegamook, Quebec, Canada",
    "Saint-Eustache, Quebec, Canada",
    "East Gwillimbury, Ontario, Canada",
    "Riviere-du-Loup, Quebec, Canada",
    "Contrecoeur, Quebec, Canada",
    "Kanata, Ontario, Canada",
    "Chelsea, Quebec, Canada",
    "Pelham, Ontario, Canada",
    "Mount Pearl, Newfoundland and Labrador, Canada",
    "Louiseville, Quebec, Canada",
    "Val-d'Or, Quebec, Canada",
    "Dolbeau-Mistassini, Quebec, Canada",
    "Simcoe, Ontario, Canada",
    "La Tuque, Quebec, Canada",
    "Coaticook, Quebec, Canada",
    "Lawrencetown, Nova Scotia, Canada",
    "Creston, British Columbia, Canada",
    "Neepawa, Manitoba, Canada",
    "Sutton, Quebec, Canada",
    "Repentigny, Quebec, Canada",
    "Swan Hills, Alberta, Canada",
    "Kirkland Lake, Ontario, Canada",
    "Thessalon, Ontario, Canada",
    "Mont-Tremblant, Quebec, Canada",
    "High River, Alberta, Canada",
    "Unity, Saskatchewan, Canada",
    "Breton, Alberta, Canada",
    "Corner Brook, Newfoundland and Labrador, Canada",
    "St-Croix, Quebec, Canada",
    "Caraquet, New Brunswick, Canada",
    "Hagersville, Ontario, Canada",
    "Drummondville, Quebec, Canada",
    "Montebello, Quebec, Canada",
    "Baie-Comeau, Quebec, Canada",
    "Essex, Ontario, Canada",
    "Houston, British Columbia, Canada",
    "Morden, Manitoba, Canada",
    "Mississippi Mills, Ontario, Canada",
    "Glace Bay, Nova Scotia, Canada",
    "Napierville, Quebec, Canada",
    "Conception Bay South, Newfoundland and Labrador, Canada",
    "Windsor, Quebec, Canada",
    "Ville-Marie, Quebec, Canada",
    "Chibougamau, Quebec, Canada",
    "Biggar, Saskatchewan, Canada",
    "Weyburn, Saskatchewan, Canada",
    "Lac-Delage, Quebec, Canada",
    "Dauphin, Manitoba, Canada",
    "Bedford, Quebec, Canada",
    "Cote Saint-Luc, Quebec, Canada",
    "Annapolis Royal, Nova Scotia, Canada",
    "Tsawwassen, British Columbia, Canada",
    "Fort Providence, Northwest Territories, Canada",
    "Edmonton, Alberta, Canada",
    "Igloolik, Nunavut, Canada",
    "Englehart, Ontario, Canada",
    "Exeter, Ontario, Canada",
    "Salaberry-de-Valleyfield, Quebec, Canada",
    "Fermont, Quebec, Canada",
    "Alert Bay, British Columbia, Canada",
    "Mascouche, Quebec, Canada",
    "Consul, Saskatchewan, Canada",
    "Maniwaki, Quebec, Canada",
    "Saint-Elzear, Quebec, Canada",
    "Lampman, Saskatchewan, Canada",
    "Laurentiens, Quebec, Canada",
    "La Sarre, Quebec, Canada",
    "Vallee-Jonction, Quebec, Canada",
    "La Guadeloupe, Quebec, Canada",
    "Saint George, New Brunswick, Canada",
    "Geraldton, Ontario, Canada",
    "Chelsea, Quebec, Canada",
    "Prescott, Ontario, Canada",
    "Saint-Jean-de-l'Ile-d'Orleans, Quebec, Canada",
    "Amos, Quebec, Canada",
    "Baden, Ontario, Canada",
    "Wawa, Ontario, Canada",
    "Saint-Louis de Kent, New Brunswick, Canada",
    "Kahnawake, Quebec, Canada",
    "St-Raymond, Quebec, Canada",
    "Bonfield, Ontario, Canada",
    "Sainte-Agathe-des-Monts, Quebec, Canada",
    "Lac-Brome, Quebec, Canada",
    "Atikokan, Ontario, Canada",
    "Bouctouche, New Brunswick, Canada",
    "Bruno, Saskatchewan, Canada",
    "Cap-de-la-Madeleine, Quebec, Canada",
    "St-Croix, Quebec, Canada",
    "Montreal, Quebec, Canada"
]

let CitiesUS = [
    "Los Angeles, California",
    "Chicago, Illinois",
    "Houston, Texas",
    "Phoenix, Arizona",
    "Philadelphia, Pennsylvania",
    "San Antonio, Texas",
    "San Diego, California",
    "Dallas, Texas",
    "San Jose, California",
    "Austin, Texas",
    "Jacksonville, Florida",
    "Fort Worth, Texas",
    "Columbus, Ohio",
    "Indianapolis, Indiana",
    "Charlotte, North Carolina",
    "San Francisco, California",
    "Louisville, Kentucky",
    "Seattle, Washington",
    "Denver, Colorado",
    "Washington, District of Columbia",
    "Boston, Massachusetts",
    "El Paso, Texas",
    "Detroit, Michigan",
    "Oklahoma City, Oklahoma",
    "Portland, Oregon",
    "Las Vegas, Nevada",
    "Memphis, Tennessee",
    "Baltimore, Maryland",
    "Milwaukee, Wisconsin",
    "Albuquerque, New Mexico",
    "Tucson, Arizona",
    "Fresno, California",
    "Mesa, Arizona",
    "Sacramento, California",
    "Atlanta, Georgia",
    "Kansas City, Missouri",
    "Colorado Springs, Colorado",
    "Omaha, Nebraska",
    "Raleigh, North Carolina",
    "Miami, Florida",
    "Long Beach, California",
    "Virginia Beach, Virginia",
    "Oakland, California",
    "Minneapolis, Minnesota",
    "Tulsa, Oklahoma",
    "Tampa, Florida",
    "Arlington, Texas",
    "New Orleans, Louisiana",
    "Wichita, Kansas",
    "Bakersfield, California",
    "Cleveland, Ohio",
    "Aurora, Colorado",
    "Anaheim, California",
    "Santa Ana, California",
    "Riverside, California",
    "Corpus Christi, Texas",
    "Henderson, Nevada",
    "Stockton, California",
    "St. Paul, Minnesota",
    "Cincinnati, Ohio",
    "St. Louis, Missouri",
    "Pittsburgh, Pennsylvania",
    "Greensboro, North Carolina",
    "Lincoln, Nebraska",
    "Plano, Texas",
    "Orlando, Florida",
    "Irvine, California",
    "Newark, New Jersey",
    "Durham, North Carolina",
    "Chula Vista, California",
    "Toledo, Ohio",
    "Fort Wayne, Indiana",
    "St. Petersburg, Florida",
    "Laredo, Texas",
    "Jersey City, New Jersey",
    "Chandler, Arizona",
    "Madison, Wisconsin",
    "Lubbock, Texas",
    "Scottsdale, Arizona",
    "Reno, Nevada",
    "Buffalo, New York",
    "Glendale, Arizona",
    "North Las Vegas, Nevada",
    "Winston-Salem, North Carolina",
    "Chesapeake, Virginia",
    "Norfolk, Virginia",
    "Fremont, California",
    "Garland, Texas",
    "Irving, Texas",
    "Hialeah, Florida",
    "Richmond, Virginia",
    "Boise City, Idaho",
    "Spokane, Washington",
    "Baton Rouge, Louisiana",
    "Tacoma, Washington",
    "San Bernardino, California",
    "Modesto, California",
    "Fontana, California",
    "Des Moines, Iowa",
    "Moreno Valley, California",
    "Santa Clarita, California",
    "Fayetteville, North Carolina",
    "Birmingham, Alabama",
    "Oxnard, California",
    "Rochester, New York",
    "Port St. Lucie, Florida",
    "Grand Rapids, Michigan",
    "Huntsville, Alabama",
    "Salt Lake City, Utah",
    "Frisco, Texas",
    "Yonkers, New York",
    "Amarillo, Texas",
    "Glendale, California",
    "Huntington Beach, California",
    "McKinney, Texas",
    "Montgomery, Alabama",
    "Aurora, Illinois",
    "Akron, Ohio",
    "Little Rock, Arkansas",
    "Tempe, Arizona",
    "Columbus, Georgia",
    "Overland Park, Kansas",
    "Grand Prairie, Texas",
    "Tallahassee, Florida",
    "Cape Coral, Florida",
    "Mobile, Alabama",
    "Knoxville, Tennessee",
    "Shreveport, Louisiana",
    "Worcester, Massachusetts",
    "Ontario, California",
    "Vancouver, Washington",
    "Sioux Falls, South Dakota",
    "Chattanooga, Tennessee",
    "Brownsville, Texas",
    "Fort Lauderdale, Florida",
    "Providence, Rhode Island",
    "Newport News, Virginia",
    "Rancho Cucamonga, California",
    "Santa Rosa, California",
    "Peoria, Arizona",
    "Oceanside, California",
    "Elk Grove, California",
    "Salem, Oregon",
    "Pembroke Pines, Florida",
    "Eugene, Oregon",
    "Garden Grove, California",
    "Fort Collins, Colorado",
    "Corona, California",
    "Springfield, Missouri",
    "Jackson, Mississippi",
    "Alexandria, Virginia",
    "Hayward, California",
    "Clarksville, Tennessee",
    "Lakewood, Colorado",
    "Lancaster, California",
    "Salinas, California",
    "Palmdale, California",
    "Hollywood, Florida",
    "Springfield, Massachusetts",
    "Kansas City, Kansas",
    "Sunnyvale, California",
    "Pomona, California",
    "Killeen, Texas",
    "Escondido, California",
    "Pasadena, Texas",
    "Naperville, Illinois",
    "Bellevue, Washington",
    "Joliet, Illinois",
    "Murfreesboro, Tennessee",
    "Midland, Texas",
    "Rockford, Illinois",
    "Paterson, New Jersey",
    "Savannah, Georgia",
    "Bridgeport, Connecticut",
    "Torrance, California",
    "McAllen, Texas",
    "Syracuse, New York",
    "Surprise, Arizona",
    "Denton, Texas",
    "Roseville, California",
    "Thornton, Colorado",
    "Miramar, Florida",
    "Pasadena, California",
    "Mesquite, Texas",
    "Olathe, Kansas",
    "Dayton, Ohio",
    "Carrollton, Texas",
    "Waco, Texas",
    "Orange, California",
    "Fullerton, California",
    "Charleston, South Carolina",
    "West Valley City, Utah",
    "Visalia, California",
    "Hampton, Virginia",
    "Gainesville, Florida",
    "Warren, Michigan",
    "Coral Springs, Florida",
    "Cedar Rapids, Iowa",
    "Round Rock, Texas",
    "Sterling Heights, Michigan",
    "Kent, Washington",
    "Columbia, South Carolina",
    "Santa Clara, California",
    "New Haven, Connecticut",
    "Stamford, Connecticut",
    "Concord, California",
    "Elizabeth, New Jersey",
    "Thousand Oaks, California",
    "Lafayette, Louisiana",
    "Simi Valley, California",
    "Topeka, Kansas",
    "Norman, Oklahoma",
    "Fargo, North Dakota",
    "Wilmington, North Carolina",
    "Abilene, Texas",
    "Odessa, Texas",
    "Columbia, Missouri",
    "Pearland, Texas",
    "Victorville, California",
    "Hartford, Connecticut",
    "Vallejo, California",
    "Allentown, Pennsylvania",
    "Berkeley, California",
    "Richardson, Texas",
    "Arvada, Colorado",
    "Ann Arbor, Michigan",
    "Rochester, Minnesota",
    "Cambridge, Massachusetts",
    "Sugar Land, Texas",
    "Lansing, Michigan",
    "Evansville, Indiana",
    "College Station, Texas",
    "Fairfield, California",
    "Clearwater, Florida",
    "Beaumont, Texas",
    "Independence, Missouri",
    "Provo, Utah",
    "West Jordan, Utah",
    "Murrieta, California",
    "Palm Bay, Florida",
    "El Monte, California",
    "Carlsbad, California",
    "North Charleston, South Carolina",
    "Temecula, California",
    "Clovis, California",
    "Springfield, Illinois",
    "Meridian, Idaho",
    "Westminster, Colorado",
    "Costa Mesa, California",
    "High Point, North Carolina",
    "Manchester, New Hampshire",
    "Pueblo, Colorado",
    "Lakeland, Florida",
    "Pompano Beach, Florida",
    "West Palm Beach, Florida",
    "Antioch, California",
    "Everett, Washington",
    "Downey, California",
    "Lowell, Massachusetts",
    "Centennial, Colorado",
    "Elgin, Illinois",
    "Richmond, California",
    "Peoria, Illinois",
    "Broken Arrow, Oklahoma",
    "Miami Gardens, Florida",
    "Billings, Montana",
    "Jurupa Valley, California",
    "Sandy Springs, Georgia",
    "Gresham, Oregon",
    "Lewisville, Texas",
    "Hillsboro, Oregon",
    "San Buenaventura (Ventura), California",
    "Greeley, Colorado",
    "Inglewood, California",
    "Waterbury, Connecticut",
    "League City, Texas",
    "Santa Maria, California",
    "Tyler, Texas",
    "Daly City, California",
    "Boulder, Colorado",
    "Allen, Texas",
    "West Covina, California",
    "Sparks, Nevada",
    "Wichita Falls, Texas",
    "Green Bay, Wisconsin",
    "San Mateo, California",
    "Norwalk, California",
    "Rialto, California",
    "Las Cruces, New Mexico",
    "Chico, California",
    "El Cajon, California",
    "Burbank, California",
    "South Bend, Indiana",
    "Renton, Washington",
    "Vista, California",
    "Davenport, Iowa",
    "Edinburg, Texas",
    "Tuscaloosa, Alabama",
    "Carmel, Indiana",
    "Spokane Valley, Washington",
    "San Angelo, Texas",
    "Vacaville, California",
    "Bend, Oregon",
    "Kenosha, Wisconsin",
    "Boca Raton, Florida",
    "Lee's Summit, Missouri",
    "Nampa, Idaho",
    "Rio Rancho, New Mexico",
    "South Fulton, Georgia",
    "Roanoke, Virginia",
    "Beaverton, Oregon",
    "Yuma, Arizona",
    "Lawrence, Kansas",
    "Orem, Utah",
    "Longmont, Colorado",
    "San Marcos, California",
    "Albany, New York",
    "Sandy, Utah",
    "Concord, North Carolina",
    "Federal Way, Washington",
    "Hesperia, California",
    "Brockton, Massachusetts",
    "Compton, California",
    "Flint, Michigan",
    "Erie, Pennsylvania",
    "New Bedford, Massachusetts",
    "Fishers, Indiana",
    "Sunrise, Florida",
    "Roswell, Georgia",
    "Menifee, California",
    "Tracy, California",
    "Plantation, Florida",
    "Quincy, Massachusetts",
    "Portsmouth, Virginia",
    "Mission Viejo, California",
    "Chino, California",
    "Lynn, Massachusetts",
    "Edmond, Oklahoma",
    "Dearborn, Michigan",
    "Livonia, Michigan",
    "Yakima, Washington",
    "South Gate, California",
    "Greenville, North Carolina",
    "Lawton, Oklahoma",
    "Kirkland, Washington",
    "Asheville, North Carolina",
    "Deltona, Florida",
    "Redding, California",
    "Bellingham, Washington",
    "Suffolk, Virginia",
    "Indio, California",
    "Carson, California",
    "Santa Barbara, California",
    "Conroe, Texas",
    "Westminster, California",
    "Santa Monica, California",
    "New Braunfels, Texas",
    "Livermore, California",
    "Palm Coast, Florida",
    "St. George, Utah",
    "Fall River, Massachusetts",
    "Nashua, New Hampshire",
    "Champaign, Illinois",
    "Miami Beach, Florida",
    "Norwalk, Connecticut",
    "San Leandro, California",
    "O'Fallon, Missouri",
    "Newton, Massachusetts",
    "Reading, Pennsylvania",
    "Avondale, Arizona",
    "Fort Smith, Arkansas",
    "Citrus Heights, California",
    "Ogden, Utah",
    "Fayetteville, Arkansas",
    "Fort Myers, Florida",
    "Goodyear, Arizona",
    "Bryan, Texas",
    "Waukegan, Illinois",
    "Hawthorne, California",
    "Redwood City, California",
    "Hoover, Alabama",
    "Bloomington, Indiana",
    "Duluth, Minnesota",
    "Lake Forest, California",
    "Hemet, California",
    "Whittier, California",
    "Clifton, New Jersey",
    "Largo, Florida",
    "Bloomington, Minnesota",
    "Danbury, Connecticut",
    "Santa Fe, New Mexico",
    "Johns Creek, Georgia",
    "Newport Beach, California",
    "Kennewick, Washington",
    "Mission, Texas",
    "Milpitas, California",
    "Troy, Michigan",
    "Chino Hills, California",
    "Alhambra, California",
    "Merced, California",
    "Trenton, New Jersey",
    "Franklin, Tennessee",
    "Medford, Oregon",
    "Melbourne, Florida",
    "Manteca, California",
    "Mountain View, California",
    "Sioux City, Iowa",
    "Lynchburg, Virginia",
    "Buena Park, California",
    "Pleasanton, California",
    "Longview, Texas",
    "Westland, Michigan",
    "Auburn, Washington",
    "Cranston, Rhode Island",
    "Somerville, Massachusetts",
    "Folsom, California",
    "Springdale, Arkansas",
    "Deerfield Beach, Florida",
    "Warwick, Rhode Island",
    "Farmington Hills, Michigan",
    "Brooklyn Park, Minnesota",
    "Lawrence, Massachusetts",
    "Plymouth, Minnesota",
    "Buckeye, Arizona",
    "Georgetown, Texas",
    "Cedar Park, Texas",
    "Tustin, California",
    "Lakewood, California",
    "Perris, California",
    "Pharr, Texas",
    "Loveland, Colorado",
    "Boynton Beach, Florida",
    "New Rochelle, New York",
    "Temple, Texas",
    "Lake Charles, Louisiana",
    "Jonesboro, Arkansas",
    "Napa, California",
    "Parma, Ohio",
    "Layton, Utah",
    "Alameda, California",
    "Warner Robins, Georgia",
    "Rapid City, South Dakota",
    "Bloomington, Illinois",
    "Gastonia, North Carolina",
    "Baytown, Texas",
    "Upland, California",
    "Racine, Wisconsin",
    "Scranton, Pennsylvania",
    "South Jordan, Utah",
    "Bellflower, California",
    "Kalamazoo, Michigan",
    "San Ramon, California",
    "Bethlehem, Pennsylvania",
    "Wyoming, Michigan",
    "Hammond, Indiana",
    "Missoula, Montana",
    "Missouri City, Texas",
    "Pasco, Washington",
    "Baldwin Park, California",
    "Iowa City, Iowa",
    "Rancho Cordova, California",
    "Rock Hill, South Carolina",
    "Flagstaff, Arizona",
    "Gary, Indiana",
    "St. Joseph, Missouri",
    "Rochester Hills, Michigan",
    "Framingham, Massachusetts",
    "Union City, California",
    "Appleton, Wisconsin",
    "Turlock, California",
    "Camden, New Jersey",
    "Bismarck, North Dakota",
    "Evanston, Illinois",
    "Woodbury, Minnesota",
    "Kissimmee, Florida",
    "Southfield, Michigan",
    "Maple Grove, Minnesota",
    "Pittsburg, California",
    "New Britain, Connecticut",
    "Jacksonville, North Carolina",
    "Mansfield, Texas",
    "Waukesha, Wisconsin",
    "Frederick, Maryland",
    "Albany, Georgia",
    "Pawtucket, Rhode Island",
    "Redmond, Washington",
    "Lauderhill, Florida",
    "Lafayette, Indiana",
    "Gulfport, Mississippi",
    "Redlands, California",
    "Weston, Florida",
    "St. Charles, Missouri",
    "Decatur, Illinois",
    "North Port, Florida",
    "North Richland Hills, Texas",
    "Greenville, South Carolina",
    "Bowling Green, Kentucky",
    "Broomfield, Colorado",
    "Canton, Ohio",
    "Marysville, Washington",
    "Walnut Creek, California",
    "Wilmington, Delaware",
    "Camarillo, California",
    "Lynwood, California",
    "Lehi, Utah",
    "Passaic, New Jersey",
    "Homestead, Florida",
    "Delray Beach, Florida",
    "Davis, California",
    "Lake Elsinore, California",
    "Daytona Beach, Florida",
    "Dothan, Alabama",
    "Rocklin, California",
    "Eau Claire, Wisconsin",
    "Rogers, Arkansas",
    "St. Cloud, Minnesota",
    "Bossier City, Louisiana",
    "Rockville, Maryland",
    "Muncie, Indiana",
    "Gaithersburg, Maryland",
    "Union City, New Jersey",
    "West Des Moines, Iowa",
    "South San Francisco, California",
    "Yorba Linda, California",
    "Conway, Arkansas",
    "Lodi, California",
    "Ankeny, Iowa",
    "Mount Vernon, New York",
    "Rowlett, Texas",
    "Waterloo, Iowa",
    "Lakeville, Minnesota",
    "Alpharetta, Georgia",
    "Jackson, Tennessee",
    "Yuba City, California",
    "Oshkosh, Wisconsin",
    "Victoria, Texas",
    "Johnson City, Tennessee",
    "Redondo Beach, California",
    "Tamarac, Florida",
    "Laguna Niguel, California",
    "Eagan, Minnesota",
    "Kenner, Louisiana",
    "Auburn, Alabama",
    "Ames, Iowa",
    "Portland, Maine",
    "North Little Rock, Arkansas",
    "Sammamish, Washington",
    "Madera, California",
    "Shawnee, Kansas",
    "Doral, Florida",
    "Blaine, Minnesota",
    "Tulare, California",
    "Youngstown, Ohio",
    "Pflugerville, Texas",
    "Palo Alto, California",
    "Schenectady, New York",
    "Harlingen, Texas",
    "Bayonne, New Jersey",
    "Eden Prairie, Minnesota",
    "Port Orange, Florida",
    "Dublin, California",
    "San Marcos, Texas",
    "Noblesville, Indiana",
    "Santa Cruz, California",
    "Janesville, Wisconsin",
    "San Clemente, California",
    "Brentwood, California",
    "East Orange, New Jersey",
    "Cheyenne, Wyoming",
    "Eastvale, California",
    "Haverhill, Massachusetts",
    "Lorain, Ohio",
    "Grand Junction, Colorado",
    "Springfield, Oregon",
    "Coon Rapids, Minnesota",
    "Idaho Falls, Idaho",
    "North Miami, Florida",
    "Encinitas, California",
    "Leander, Texas",
    "Waltham, Massachusetts",
    "Council Bluffs, Iowa",
    "Hamilton, Ohio",
    "Moore, Oklahoma",
    "Pico Rivera, California",
    "Montebello, California",
    "Millcreek, Utah",
    "Sanford, Florida",
    "National City, California",
    "Burnsville, Minnesota",
    "Coconut Creek, Florida",
    "Lakewood, Washington",
    "Taylor, Michigan",
    "Novi, Michigan",
    "Marietta, Georgia",
    "Ocala, Florida",
    "Terre Haute, Indiana",
    "Woodland, California",
    "Petaluma, California",
    "La Habra, California",
    "Malden, Massachusetts"
]

let PopularTitleData = {
    titleOfSection: "Popular Job Titles",
    items: []
};

let PopularCities = {
    titleOfSection: "Popular Cities",
    items: []
};

function capitalizeFirstLetter(string) {
    return string.charAt(0).toUpperCase() + string.slice(1);
}

const getByJobTitle = function (params) {
    let geo = "us";
    let KeywordsArr = JSON.parse(JSON.stringify(KeywordsUk));
    let popularTitleData = JSON.parse(JSON.stringify(PopularTitleData));

    if (params && params.geo && params.geo.length == 2) {
        geo = params.geo.toLowerCase();
    }

    if (geo == "uk") {
        geo = "gb"
    }

    for (let index in KeywordsArr) {
        let item = KeywordsArr[index];

        item = item.toLowerCase();
        item = capitalizeFirstLetter(item);

        let FriendlyUrl = FriendlyJobSerpCreate({keyword: item, geo: geo});

        if (FriendlyUrl && typeof FriendlyUrl == "string") {
            let tmpObj = {
                title: item + " jobs",
                link: "/" + FriendlyUrl
            }
            popularTitleData.items.push(tmpObj)
        }
    }

    return popularTitleData;

}

const getByLocation = function (params) {
    let geo = "us";
    let CitiesArr = JSON.parse(JSON.stringify(CitiesUS));
    let PopularCitiesData = JSON.parse(JSON.stringify(PopularCities));

    if (params && params.geo && params.geo.length == 2) {
        geo = params.geo.toLowerCase();
    }

    if (geo == "uk") {
        geo = "gb"
    }

    if (geo == "gb") {
        CitiesArr = JSON.parse(JSON.stringify(CitiesUK));
    }

    if (geo == "ca") {
        CitiesArr = JSON.parse(JSON.stringify(CitiesCA));
    }

    for (let index in CitiesArr) {
        let item = CitiesArr[index];

        item = item.toLowerCase();
        item = capitalizeFirstLetter(item);

        let FriendlyUrl = FriendlyJobSerpCreate({location: item, geo: geo});

        if (FriendlyUrl && typeof FriendlyUrl == "string") {
            let tmpObj = {
                title: item,
                link: "/" + FriendlyUrl
            }
            PopularCitiesData.items.push(tmpObj)
        }
    }

    return PopularCitiesData;

}

module.exports = {
    jobTitle: getByJobTitle,
    location:getByLocation
}